[package]
name = "msg-server"
version = "0.1.0"
edition = "2021"

[dependencies]
abi = { path = "../abi" }
db = { path = "../db" }

thiserror = { version = "1.0" }
rdkafka = { version = "0.36.2", features = ["cmake-build"] }
