[workspace]
members = [
    "abi",
    "api",
    "cache",
    "client",
    "msg-gateway",
    "db",
    "entity",
    "migration",
    "msg-server",
]
resolver = "2"

[profile.dev]
incremental = true
