[package]
name = "chat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
abi = { path = "../abi" }

rdkafka = { version = "0.36.2", features = ["cmake-build"] }
serde_json = { version = "1.0" }
