[package]
name = "abi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = { version = "0.11.0", features = ["gzip"] }
prost = "0.12"
prost-types = "0.12.3"


[build-dependencies]
tonic-build = "0.11.0"
