[package]
name = "abi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-util = { version = "0.7", features = ["codec"] }
tonic = { version = "0.11.0", features = ["gzip"] }
prost = "0.12"
prost-types = "0.12.3"
tokio = { version = "1.37", features = ["full"] }
dashmap = { version = "5.3" }
tracing = { version = "0.1.40", features = ["log"] }
tracing-subscriber = "0.3.18"
bincode = "1.3.3"
serde = { version = "1", features = ["derive"] }
bytes = { version = "1.6" }
futures = { version = "0.3" }
thiserror = { version = "1.0" }

[build-dependencies]
tonic-build = "0.11.0"
